DOMA-2527 fixed cancle edit action. Add state editCanseled
open-condo-software/condo pull request #1519
Opened 2022-05-04 06:30 UTC by VKislov

There were two options to write a handleChange function and use it instead of handleSave in onChange. Or just add an non-save condition to handleSave.
Initially, it was just changing the mod to 'display' to cancel, but since onChange uses handleSave, any content change is always saved

2022-05-04 06:32 UTC, SavelevMatthew approved these changes

2022-05-04 06:32 UTC, SavelevMatthew commented on apps/condo/domains/common/components/Comments/Comment.tsx
> +    const [editCanceled, setEditCanceled] = useState<boolean>(false)
If you provide `false` as default values, hook will automatically generate boolean type

2022-05-04 06:39 UTC, dkoviazin commented on apps/condo/domains/common/components/Comments/Comment.tsx
> +        if (editCanceled) {
Maybe, 
```js
if (!editCanceled) { ...
```

2022-05-04 06:40 UTC, sitozzz approved these changes

2022-05-04 07:06 UTC, pahaz commented
Why you add a new submode here?

2022-05-04 07:06 UTC, pahaz commented
Remove merge commit. Use rebase

2022-05-04 07:11 UTC, dkoviazin approved these changes

2022-05-04 07:14 UTC, dkoviazin requested changes
Condo submodule

2022-05-04 08:42 UTC, dkoviazin approved these changes

2022-05-04 09:24 UTC, AntonAL reviewed
You have two buttons with same `key="save"`

2022-05-04 09:33 UTC, AntonAL requested changes

2022-05-04 09:33 UTC, AntonAL commented on apps/condo/domains/common/components/Comments/Comment.tsx
> +        setEditCanceled(true)
I've tested it locally, when you click cancel, you cannot save edited text anymore.
It's because `editCanceled` is set permanently here.

2022-05-11 06:57 UTC, VKislov commented
Comment component has been changed and now this PR is not relevant. The task was solved with another PR

2022-05-11 06:57 UTC, closed without merging