DOMA-2996 Removed the watchers field from the Ticket model
open-condo-software/condo pull request #1605
Opened 2022-05-17 06:32 UTC by VKislov

Removed the watchers field from the Ticket model. Removed the watchers resolver in TicketChange. Created a migration.

2022-05-17 08:08 UTC, VKislov commented
Removed traces of watchers in ticket gql, tests and schema.ts

2022-05-17 10:40 UTC, dkoviazin approved these changes

2022-05-17 16:40 UTC, AntonAL approved these changes

2022-05-18 06:14 UTC, sitozzz requested changes
Plz recreate migration file

2022-05-18 06:46 UTC, sitozzz approved these changes

2022-05-18 07:26 UTC, merged