Fix/condo/doma 1896/upeate icons
open-condo-software/condo pull request #1634
Opened 2022-05-23 12:15 UTC by VKislov

Сhanged side menu icons according to the layout.
Before: 
![image](https://user-images.githubusercontent.com/64303474/169537022-659b7301-ef54-493c-bde7-335debe7fe0f.png)

After: 
![image](https://user-images.githubusercontent.com/64303474/169536824-68a26d0e-2c87-47f7-9675-eccfce5df6fe.png)
Layout: https://www.figma.com/file/P827yyueCLRT6o4gyNtzY6/CRM-(v1.doma.ai)?node-id=20802%3A105102

Created from PR: https://github.com/open-condo-software/condo/pull/1629
Recreated branch because the branch was not deployed for review

2022-05-24 06:12 UTC, VKislov commented
I left `BarMiniAppsIcon` uncompressed because after processing the fill does not work correctly.

2022-05-24 18:17 UTC, sitozzz approved these changes

2022-05-25 13:20 UTC, akarjakin approved these changes

2022-05-25 14:11 UTC, SavelevMatthew requested changes
As far as I remember we have monochromatic icons, yours are two-coloured. You should pass design review before merging this PR. And why are you passing viewbox as prop and not height and width?

2022-05-26 12:29 UTC, SavelevMatthew approved these changes
Now looks as designed...LGTM

2022-05-26 12:31 UTC, SavelevMatthew commented on apps/condo/domains/common/components/icons/BarBillingIcon.tsx
> +        <svg width="20" height="20" fill="none" viewBox={viewBox} xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M4 2h12c1.1046 0 2 .8954 2 2v5H2V4c0-1.1046.8954-2
Please don't use more than 1 tag in single line....It makes it harder to read

2022-05-30 05:10 UTC, merged