Feature/condo/doma 2676/refaktoring for classifier
open-condo-software/condo pull request #1742
Opened 2022-06-14 07:09 UTC by VKislov

Partial replacement of using a three-level classifier with just using `classifierRule`. Correction of table column rendering functions related to this change on the ticket page.
Remove obsolete `TicketClassifier`. Rebase and resolve conflicts. Created migration and generated types.

2022-07-03 07:00 UTC, pahaz commented
It look like there is no test.js changes. Could you please add this fields to the tests.

2022-07-07 17:57 UTC, AntonAL requested changes

2022-07-07 17:57 UTC, AntonAL commented on apps/condo/migrations/20220705094338-0143_remove_ticket_categoryclassifier_and_more.js
> +ALTER TABLE "Ticket" DROP COLUMN "placeClassifier" CASCADE;
With this migration you will just wipe out all information on classifier. Data transfer SQL-queries should be executed first and then you can drop all unnecessary columns.

2022-07-11 06:18 UTC, VKislov commented
There were about 50 tickets with unidentified classifierRule. Because of this, such tickets will not be classified. It is necessary to write a script that put down the classifierRule everywhere in accordance with the combination of category, place, problem classifiers specified in the ticket.
![Screenshot from 2022-07-11 10-50-07](https://user-images.githubusercontent.com/64303474/178200656-a7bde8f0-ab7f-456e-93ea-a64cc48e92d2.png)

2022-07-14 09:13 UTC, dkoviazin approved these changes

2022-07-21 10:03 UTC, AntonAL approved these changes

2022-07-21 16:40 UTC, merged

2022-07-22 06:01 UTC, pahaz commented on apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
> +                console.log(ticketChange['classifierRuleDisplayNameFrom'])
?

2022-07-22 06:02 UTC, pahaz commented on apps/condo/domains/ticket/components/TicketChanges/TicketChange.tsx
> +        ['classifierRuleDisplayName', ClassifierMessage],
classifierDisplayName

2022-07-22 06:07 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "Ticket" DROP COLUMN "placeClassifier" CASCADE;
Comment

2022-07-22 06:07 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "Ticket" DROP COLUMN "problemClassifier" CASCADE;
Comment

2022-07-22 06:07 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "TicketChange" DROP COLUMN "categoryClassifierDisplayNameFrom" CASCADE;
Comment

2022-07-22 06:07 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "TicketChange" DROP COLUMN "categoryClassifierDisplayNameTo" CASCADE;
Comment

2022-07-22 06:07 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "TicketChange" DROP COLUMN "categoryClassifierIdFrom" CASCADE;
Comment