DOMA-3361 added returned checkbox on ticket index page
open-condo-software/condo pull request #1816
Opened 2022-06-24 06:49 UTC by nomerdvadcatpyat

2022-06-24 07:05 UTC, sitozzz requested changes
Please change `eventName` and `data-cy` props of new `Checkbox`

2022-06-24 07:05 UTC, sitozzz commented on apps/condo/pages/ticket/index.tsx
> +                                                                        data-cy={'ticket__filter-isWarranty'}
You should use unique string id for cypress attributes. This may break the test!

2022-06-24 07:05 UTC, sitozzz commented on apps/condo/pages/ticket/index.tsx
> +                                                                        eventName={'TicketFilterCheckboxWarranty'}
`eventName` prop is used for sending analytics data. Please use unique identifier

2022-06-24 07:06 UTC, akarjakin requested changes

2022-06-24 07:06 UTC, akarjakin commented on apps/condo/domains/ticket/hooks/useReturnedSearch.ts
> +    const handleIsPaidChange = (e: CheckboxChangeEvent): void => {
this function is redundant and it lakes useCallback. Please combine it with `setIsReturned `

2022-06-24 07:45 UTC, sitozzz approved these changes

2022-06-27 16:34 UTC, AntonAL commented on apps/condo/domains/ticket/hooks/useReturnedSearch.ts
> +export const useReturnedSearch = <F>(loading: boolean): [boolean, (e: CheckboxChangeEvent) => void] => {
Could you please extract types from this line. It's hard to read 😵‍💫

2022-06-28 07:58 UTC, dkoviazin approved these changes

2022-06-28 08:15 UTC, merged