DOMA-3204 simplify CI test running command
open-condo-software/condo pull request #1863
Opened 2022-07-03 09:29 UTC by pahaz

2022-07-03 10:54 UTC, toplenboren approved these changes

2022-07-04 04:54 UTC, akarjakin approved these changes

2022-07-08 05:48 UTC, akarjakin requested changes

2022-07-08 05:48 UTC, akarjakin commented on .github/workflows/nodejs.condo.test.yml
> +          yarn workspace @app/condo test --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/schema/(.*)[.]test.js$' 2>&1 > condo.test.log
it's done here https://github.com/open-condo-software/condo/pull/1892

2022-07-28 19:28 UTC, closed without merging