DOMA-3446 added output of registry exchange integration errors (upd s…
open-condo-software/condo pull request #1918
Opened 2022-07-14 11:20 UTC by Alllex202

…ubmodule)

2022-07-14 11:20 UTC, AleX83Xpert approved these changes

2022-07-14 11:21 UTC, VKislov approved these changes

2022-07-15 13:08 UTC, akarjakin requested changes
Please add tests for domains/registry/utils/helpers.js

2022-07-18 06:39 UTC, Alllex202 commented
> Please add tests for domains/registry/utils/helpers.js

I added tests

2022-07-19 08:03 UTC, toplenboren approved these changes

2022-07-22 10:15 UTC, merged