HOTFIX commented remove colomns category place problem
open-condo-software/condo pull request #1962
Opened 2022-07-22 12:02 UTC by VKislov

2022-07-22 12:03 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +Add field classifierRuleDisplayNameTo to ticketchange
?

2022-07-22 12:03 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +Add field classifierRuleIdTo to ticketchange
?

2022-07-22 12:04 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +--ALTER TABLE "TicketHistoryRecord" ADD COLUMN "problemClassifier" uuid NULL;
`ALTER TABLE table_name ADD COLUMN IF NOT EXISTS column_name INTEGER;`

2022-07-22 15:21 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
>  CREATE INDEX "Ticket_problemClassifier_f1bfcd39" ON "Ticket" ("problemClassifier");
if not exists

2022-07-22 15:21 UTC, pahaz commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
>  CREATE INDEX "Ticket_placeClassifier_01e3ec3a" ON "Ticket" ("placeClassifier");
if not exists

2022-07-22 15:33 UTC, AntonAL commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
>  SET CONSTRAINTS "Ticket_placeClassifier_01e3ec3a_fk_TicketPlaceClassifier_id" IMMEDIATE; ALTER TABLE "Ticket" DROP CONSTRAINT "Ticket_placeClassifier_01e3ec3a_fk_TicketPlaceClassifier_id";
If we want to save `Ticket.placeClassifier` column, maybe we don't need to drop a constraint. It does not disturbs us, AFAIK.

2022-07-22 15:33 UTC, AntonAL commented on apps/condo/migrations/20220721202935-0153_remove_ticket_placeclassifier_and_more.js
> +ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "placeClassifier" uuid NULL CONSTRAINT "Ticket_placeClassifier_01e3ec3a_fk_TicketPlaceClassifier_id" REFERENCES "TicketPlaceClassifier"("id") DEFERRABLE
First command in this line throws an error.
Check whether you already have this constraint locally.

2022-07-22 15:34 UTC, AntonAL commented
A `Ticket` schema has a comment `// Todo(zuch): add placeClassifier, categoryClassifier and classifierRule`, make sure that this comment is actual.

2022-07-25 15:23 UTC, AntonAL commented
Before merging, let's take a look at it together.
Invite me in a meet.

2022-08-03 12:11 UTC, pahaz requested changes
Looks to strange

2022-08-09 15:48 UTC, VKislov commented on apps/condo/migrations/20220801183319-0160_rename_classifierruledisplaynamefrom_ticketchange_classifierdisplaynamefrom_and_more.js
> +--ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "classifier" uuid NULL CONSTRAINT "Ticket_classifier_7a786997_fk_TicketClassifierRule_id" REFERENCES "TicketClassifierRule"("id") DEFERRABLE INITIALLY
need to add constrain

2022-08-11 10:12 UTC, AntonAL commented
Not actual.
All the changes was merged in PR https://github.com/open-condo-software/condo/pull/2074/files

2022-08-11 10:12 UTC, closed without merging