SBERDOMA-117 setup keystone sessionStore connection
open-condo-software/condo pull request #201
Opened 2021-06-25 09:07 UTC by sitozzz

2021-06-25 09:10 UTC, dkoviazin commented on apps/condo/package.json
> +    "connect-redis": "^6.0.0",
Is it possible to use 'io-redis' which we already have?

2021-06-25 10:49 UTC, dkoviazin approved these changes
Ok

2021-06-25 13:11 UTC, pahaz commented on packages/@core.keystone/setup.utils.js
> +const { COOKIE_MAX_AGE } = require('@condo/domains/user/constants/common')
you don't need to extract a const if you don't know any reusable case for this const

2021-06-25 13:12 UTC, pahaz requested changes

2021-06-25 13:12 UTC, pahaz commented on packages/@core.keystone/setup.utils.js
> +const { COOKIE_MAX_AGE } = require('@condo/domains/user/constants/common')
You can't use const form apps in packages!

2021-06-25 13:13 UTC, pahaz commented on packages/@core.keystone/setup.utils.js
> +            maxAge: COOKIE_MAX_AGE,
you can take it from config or leave the default value

2021-06-26 10:24 UTC, pahaz commented on apps/condo/package.json
> +    "express-session": "^1.17.2",
if you put the logic inside @core/keystone you should move the requirenebts inside `packages/@core.keystone/packages.json`

2021-06-27 06:36 UTC, pahaz approved these changes

2021-06-27 06:37 UTC, merged