DOMA-3751 added lastCommentAt and completedAt to omit ticket change trackable fields
open-condo-software/condo pull request #2023
Opened 2022-08-01 07:36 UTC by nomerdvadcatpyat

2022-08-01 10:31 UTC, dkoviazin approved these changes

2022-08-02 06:24 UTC, sitozzz requested changes
Please recreate migration file to avoid conflicts

2022-08-03 12:13 UTC, pahaz approved these changes

2022-08-08 06:35 UTC, sitozzz approved these changes

2022-08-08 07:12 UTC, merged