Fix/condo/doma 3099/added filtering processing tasks on frontend
open-condo-software/condo pull request #2042
Opened 2022-08-03 15:16 UTC by AntonAL

Filtering on backend is not enough because for User with `isAdmin` flag we need to:
- return all tasks in Keystone admin section
- return only his own tasks in "public" section

2022-08-03 16:36 UTC, sitozzz reviewed
Need to test it locally again with miniapp flow

2022-08-03 16:36 UTC, sitozzz commented on apps/condo/domains/common/components/tasks/index.tsx
> +import { User } from '../../../../schema'
absolute import please

2022-08-03 16:36 UTC, sitozzz commented on apps/condo/domains/common/components/tasks/storage/TasksLocalStorage.tsx
> +        const records = tasks.filter(task => task.status === status && task.user && task.user.id === user.id)
```suggestion
        const records = tasks.filter(task => task.status === status && get(task, 'user.id') === user.id)
```

2022-08-04 05:15 UTC, AleX83Xpert approved these changes

2022-08-04 05:15 UTC, AleX83Xpert commented on apps/condo/domains/common/components/tasks/index.tsx
> +import { User } from '../../../../schema'
```suggestion
import { User } from '@app/condo/schema'
```

2022-08-04 07:19 UTC, sitozzz requested changes
There is some issues with auth. You need to handle this cases

<img width="978" alt="Screenshot 2022-08-04 at 12 10 14" src="https://user-images.githubusercontent.com/25844927/182787405-10e92a2b-e65f-4486-9422-bfde0b97ed39.png">

<img width="989" alt="Screenshot 2022-08-04 at 11 22 19" src="https://user-images.githubusercontent.com/25844927/182787444-bee283be-85d8-4bb6-a791-cda6186c387b.png">

2022-08-04 08:48 UTC, AntonAL commented
Resolved the issues "Cannot read properties" and other.
They are related to wrong hooks usage.

2022-08-04 08:57 UTC, sitozzz approved these changes
Now it's ok

2022-08-04 09:28 UTC, merged