DOMA-4185 Added new create/delete/update access check in canManageEmployees
open-condo-software/condo pull request #2364
Opened 2022-10-05 06:56 UTC by VKislov

Added 3 new fields to the `OrganizationEmployeeRole` table: `canCreateEmployees`, `canUpdateEmployees`, `canDeleteEmployees`. Used them in the `canManageEmployees` access. Wrote tests for new accessories. In migration, I set the necessary role accesses in existing organizations in accordance with the table from the task. In new organizations, the correct accesses will be set as default when created.

2022-10-12 15:53 UTC, akarjakin commented on apps/condo/domains/organization/access/OrganizationEmployee.js
> +        let updatePermission = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, employeeToEdit.organization, 'canUpdateEmployees')
```
const accessType = originalInput.deletedAt ? 'canDeleteEmployees' : 'canUpdateEmployees'
const updatePermission = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, employeeToEdit.organization, accessType)
```

2022-10-13 05:53 UTC, akarjakin commented on apps/condo/migrations/20221013103705-0177_organizationemployeerole_cancreateemployees_and_more.js
> +-- set canCreateEmployees to true and canManageEmployees to false for Foreman employee role
1. no need for 3 updates, 1 should be enough
2. use CAPS for SQL commands like SELECT, SET, WHERE, ...
3. no DOWN migration updates reverting these changes
4. looks like this updates should be moved to scripts.

2022-10-13 06:39 UTC, pahaz commented on apps/condo/domains/organization/schema/OrganizationEmployeeRole.js
> +        canCreateEmployees: { type: Checkbox, defaultValue: false },
Use canManageEmployees for crud actions

2022-10-13 06:44 UTC, pahaz requested changes

2022-10-13 07:38 UTC, SavelevMatthew commented on apps/condo/domains/organization/access/OrganizationEmployee.js
> +        return !!(employeeRole && (employeeRole.canManageEmployees || createPermission))
Why old `canManage` and `canCreate` at the same time?

2022-10-13 07:38 UTC, SavelevMatthew commented on apps/condo/pages/employee/[id]/index.tsx
> +    const isEmployeeEditable = get(link, ['role', 'canManageEmployees'], null) || get(link, ['role', 'canUpdateEmployees'], null)
It's a bit strange to keep old and new format at the same time...
I'm 100% sure someone else will forget about it later...

So I guess you need to migrate old format to new or smth...

2022-10-17 13:47 UTC, AntonAL commented on apps/condo/domains/organization/access/OrganizationEmployee.js
> +        const createPermission = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, organizationId, 'canCreateEmployees')
A name `createPermission` looks like an action

```suggestion
        const permissionOnCreate = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, organizationId, 'canCreateEmployees')
```

2022-10-17 13:50 UTC, AntonAL commented on apps/condo/domains/organization/access/OrganizationEmployee.js
> +        const updatePermission = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, employeeToEdit.organization, accessType)
```suggestion
        const permissionOnUpdate = await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, employeeToEdit.organization, accessType)
```

2022-10-25 08:45 UTC, VKislov commented
Rebased and added UPDATE canManageEmployee for Manager role

2022-10-25 09:47 UTC, pahaz commented on apps/condo/domains/organization/access/InviteNewOrganizationEmployeeService.js
> +    return !!(employeeRole && permissionOnCreate)
```suggestion
    return await checkPermissionInUserOrganizationOrRelatedOrganization(user.id, organizationId, 'canInviteNewOrganizationEmployees')
```

2022-10-25 09:48 UTC, pahaz approved these changes

2022-10-26 12:20 UTC, merged