feat(condo): DOMA-4305 not required BankAccount.property field
open-condo-software/condo pull request #2855
Opened 2023-02-06 09:25 UTC by AntonAL

In upcoming feature to sync accounts from SBBOL it will be technically unknown to what property the fetched account belongs. A user will be prompted to manually connect properties to bank accounts.

Needed for https://github.com/open-condo-software/condo/pull/2625

2023-02-06 11:23 UTC, sitozzz approved these changes

2023-02-07 06:57 UTC, sitozzz requested changes
Please update migration number before merge

2023-02-07 12:53 UTC, VKislov approved these changes

2023-02-08 08:46 UTC, sitozzz approved these changes

2023-02-08 09:27 UTC, merged