feature(condo): DOMA-5272 extend meter schema to support integration
open-condo-software/condo pull request #2932
Opened 2023-02-19 18:25 UTC by dkoviazin

Added importId + importRemoteSystem to identify meter from integration
Added meta field to store additional settings from integration

2023-02-19 18:41 UTC, pahaz commented
Should we remove BillingMeter ?

2023-02-19 18:41 UTC, pahaz approved these changes

2023-02-19 20:11 UTC, SavelevMatthew commented on apps/condo/domains/meter/schema/Meter.js
> +            schemaDoc: 'Meter metadata. Can be used to store additional settings from integrations',
```suggestion
            schemaDoc: 'Meter metadata. Can be used to store additional settings from external sources, such as billing integrations or miniapps',
```

2023-02-19 20:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/schema/Meter.js
> +        importId: {
Store it in meta, that's the purpose of this field

2023-02-19 20:15 UTC, SavelevMatthew commented on apps/condo/domains/meter/schema/Meter.js
> +        importRemoteSystem: {
Why we need it here? We have `MeterReadingSource` schema to clarify, where readings are came from...

2023-02-19 20:17 UTC, SavelevMatthew requested changes
Cannot understand what's importId is doing outside of meta, which is the place for storing external information for apps / integrations / data providers and so on (according to our conventions)

It's also not clear to me, how our contractors was able to sync all their data without this changes...And then billings are creating specific fields there for your own needs. IMO they should have unified flow...Since we treat billings integrations same as miniapps

2023-02-20 07:53 UTC, SavelevMatthew approved these changes

2023-02-20 09:52 UTC, merged