feat(condo): DOMA-6527 handle sbbol errors from transaction request and write them to BankAccount meta
open-condo-software/condo pull request #3534
Opened 2023-06-29 06:14 UTC by VKislov

Refactored the handling of sbbol errors when requesting transactions and balance. Now if an error occurs, you can see the reason in `BankAccount.meta`

2023-06-29 06:42 UTC, sitozzz commented on apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
> +                meta.transactionException = transactionException ?? null
Is that a right place to store task errors? For me it would be better to save that to task meta or integration context

2023-06-29 06:46 UTC, sitozzz commented on apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
> +            }
Is that errors happen at same time? Can you please reorganize this code for improving readability?

2023-06-29 06:46 UTC, sitozzz commented on apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
> +                meta.amount = get(summary, 'data.closingBalance.amount')
Maybe double check that amount really provided by server response?)

2023-06-29 06:47 UTC, sitozzz reviewed
No tests?)

2023-06-29 07:33 UTC, VKislov commented
> No tests?)

Of course not. This is the code for interacting with sbbol, which is a black box for us. Or are you suggesting that I mock every method and all the possible responses of that method?

2023-06-29 07:36 UTC, SavelevMatthew commented
What if it throws something your codes not expect? Should it be stored somewhere?

2023-06-29 12:48 UTC, VKislov commented
> What if it throws something your codes not expect? Should it be stored somewhere?

Might be worth considering. Thanks for the comment

2023-06-29 13:21 UTC, sitozzz approved these changes

2023-06-29 19:05 UTC, sitozzz requested changes
You need to update functionality of file import scenario same way as you done it with request transactions

2023-06-30 04:26 UTC, VKislov commented on apps/condo/domains/organization/integrations/sbbol/constants.js
> +const STATEMENT_RESPONSE_PROCESSING = 'STATEMENT_RESPONSE_PROCESSING'
shared

2023-06-30 04:27 UTC, VKislov commented on apps/condo/domains/organization/integrations/sbbol/sync/requestTransactions.js
> +                    reqErrored = true
`while (!reqErrored && !allDataReceived && accessTokenIndex <= accessTokens.length) {`

2023-06-30 04:32 UTC, VKislov commented on apps/condo/domains/banking/tasks/generateReports.js
> +            amountAt: get(bankIntegrationAccountContext, 'meta.amountAt'),
Nothing. Only one client has access to this feature so far. After the deployment of the release, the cron task will write the actual data to the `integrationContext`

2023-06-30 05:34 UTC, sitozzz approved these changes

2023-06-30 12:35 UTC, merged