SBERDOMA-914 fix translates for share page and add setting locale via query param
open-condo-software/condo pull request #394
Opened 2021-08-01 14:55 UTC by leonid-d

… query param

2021-08-02 06:33 UTC, Dimitreee requested changes

2021-08-02 06:33 UTC, Dimitreee commented on apps/condo/domains/ticket/components/ShareTicketModal.tsx
> +                ? `… and more ${length} employee${length > 1 ? 's' : ''}`
add translation to ru/en locales, use FormattedMessage for string template matching

2021-08-10 07:50 UTC, pahaz commented on apps/condo/domains/ticket/components/ShareTicketModal.tsx
> +    const ShareWarningEmailAndMoreMessage = intl.formatMessage({ id: 'ticket.shareWarningEmailAndMore' }, {
it's better to use two different messages

2021-08-10 07:52 UTC, pahaz commented on packages/@core.next/intl.jsx
> +        return cookieLocale || queryLocale || headersLocale || defaultLocale
we have overridden extractReqLocale in _app.jsx

2021-08-10 11:07 UTC, leonid-d commented on packages/@core.next/intl.jsx
> +        const headersLocale = (req.query && req.query.locale) || (req.headers['accept-language'] && req.headers['accept-language'].slice(0, 2))
No. Telegram preview can't execute js. And it seems that it doesn't know about cookies. And there is no way to change the "accept-language" header in its requests to the server.

2021-08-12 15:37 UTC, MrFoxPro commented on apps/condo/lang/en.json
> -  "ticket.shareTitle": "Ticket #{number} dated {date} has been shared with you.",
№ in Russian and # IN English?

2021-08-12 17:16 UTC, MrFoxPro approved these changes

2021-08-17 09:02 UTC, Dimitreee approved these changes

2021-08-30 07:18 UTC, merged