feat(condo): DOMA-8003 add acquiring fields to Invoice
open-condo-software/condo pull request #4204
Opened 2023-12-14 14:38 UTC by VKislov

2023-12-14 14:56 UTC, nomerdvadcatpyat commented on apps/condo/domains/marketplace/schema/Invoice.js
> +            schemaDoc: 'Type of user who changed the pass. Can be employee or resident',
update schemaDoc of new fields

2023-12-15 06:45 UTC, AleX83Xpert requested changes

2023-12-15 06:45 UTC, AleX83Xpert commented on apps/condo/domains/marketplace/schema/Invoice.js
> +                const invoiceContext = await getById('InvoiceContext', item.context)
The `InvoiceContext` model is removed. Please do not use it. See #4142.
It's better to add only one virtual field that emulates context:
```js
context { integration { hostUrl canGroupReceipts currencyCode } }
```
To find these fields you should find the `AcquiringIntegrationContext` for the organization with finished `invoiceStatus`.

2023-12-15 06:45 UTC, AleX83Xpert commented on apps/condo/migrations/20231214184616-0353_invoicehistoryrecord_acquiringintegrationid_and_more.js
Migration for virtual fields? Is it really necessary?

2023-12-15 06:50 UTC, VKislov commented on apps/condo/migrations/20231214184616-0353_invoicehistoryrecord_acquiringintegrationid_and_more.js
?????

2023-12-15 09:15 UTC, AleX83Xpert commented on apps/condo/migrations/20231214184616-0353_invoicehistoryrecord_acquiringintegrationid_and_more.js
Hmmm, looks like it's normal. Sorry :)

2023-12-16 19:09 UTC, VKislov commented on apps/condo/migrations/20231214184616-0353_invoicehistoryrecord_acquiringintegrationid_and_more.js
I tried using a field type declaration not as a string but as an object from `@keystonejs/fields`
the result is the same, the field is still included in the migration.

2023-12-16 19:23 UTC, VKislov commented on apps/condo/migrations/20231214184616-0353_invoicehistoryrecord_acquiringintegrationid_and_more.js
I also did a check through a direct request to the database. When selecting from the database, instances arrive without these fields. Apparently some kind of migrator logic is special, I think you can find out something about it from @pahaz

2023-12-19 09:38 UTC, nomerdvadcatpyat approved these changes

2023-12-19 09:38 UTC, nomerdvadcatpyat commented on apps/condo/migrations/20231219124252-0354_billingreceipthistoryrecord_acquiringintegrationid_and_more.js
need to update to 0355

2023-12-20 04:29 UTC, AleX83Xpert commented on apps/condo/domains/billing/schema/BillingReceipt.js
> +                }
What about moving the fetching of AcquiringIntegration to a separate function?

2023-12-20 04:29 UTC, AleX83Xpert commented on apps/condo/domains/billing/schema/BillingReceipt.js
> +        hostUrl: {
Just a question. Is this name ok? Maybe use `acquiringHostUrl`?

2023-12-20 07:27 UTC, AleX83Xpert approved these changes

2023-12-20 09:26 UTC, merged