feat(ui): DOMA-8189 added tip component
open-condo-software/condo pull request #4262
Opened 2024-01-11 08:39 UTC by nomerdvadcatpyat

![изображение](https://github.com/open-condo-software/condo/assets/52532264/4b209255-7441-474f-8f98-56b9a9748906)
![изображение](https://github.com/open-condo-software/condo/assets/52532264/221d51dd-5382-40b3-9730-df1b871c4f45)

2024-01-11 09:30 UTC, Alllex202 commented on packages/ui/src/components/Tip/style.less
> +  padding: 4.3px;
4.3? :)

2024-01-11 09:30 UTC, Alllex202 commented on packages/ui/src/components/Tip/style.less
> +        right: 8px;
How about this?
```suggestion
        top: @condo-global-spacing-8;
        right: @condo-global-spacing-8;
```

2024-01-11 09:30 UTC, Alllex202 commented on packages/ui/src/components/Tip/tip.tsx
> +        setOpen(prev => !prev)
```suggestion
        setOpen(false)
```

2024-01-12 06:43 UTC, sitozzz commented on packages/ui/src/components/Tip/style.less
> +        right: 8px;
It's better to use global spacing variables

2024-01-12 07:45 UTC, nomerdvadcatpyat commented on packages/ui/src/components/Tip/style.less
> +  padding: 4.3px;
changed to 4

2024-01-12 08:05 UTC, sitozzz approved these changes

2024-01-12 08:19 UTC, Alllex202 approved these changes

2024-01-13 09:13 UTC, SavelevMatthew requested changes
What's the difference from current Tooltip component?
(except for the headline and visuals)

2024-01-15 05:20 UTC, nomerdvadcatpyat commented
> What's the difference from current Tooltip component? (except for the headline and visuals)

Different opening/closing behavior.
Tooltip is opened and closed by some trigger (in our case it is hover), this component closes either by clicking on the cross icon or by performing an external action (prop open). Combined with the different styles and the addition of tite/message (not just the title) there are a lot of changes to make it a Tooltip component new type.
In addition to this in UI-kit designs it is made as a separate component

2024-01-16 08:22 UTC, toplenboren commented
![image](https://github.com/open-condo-software/condo/assets/33755274/fe87647e-619e-4f76-8c62-5bb6133e2c4f)

I think we should add a little padding here, so that tip triangle does not collide with button

2024-01-16 08:22 UTC, toplenboren approved these changes

2024-01-18 11:51 UTC, SavelevMatthew commented on packages/ui/src/components/Tour/tourContext.tsx
> +    currentStep?: number
Why everything is optional?

2024-01-18 12:00 UTC, SavelevMatthew commented on packages/ui/src/components/Tour/tourContext.tsx
> +    currentStep?: number
You should provide proper default value instead

2024-01-18 12:04 UTC, SavelevMatthew commented on packages/ui/src/components/Tour/tourContext.tsx
> +    currentStep?: number
Context if basically a 3 things (types + defaults + actual values)

2024-01-18 12:12 UTC, SavelevMatthew commented on packages/ui/src/components/Tour/tourContext.tsx
> +    currentStep?: number
So you can solve it like this:

1. Types. You should say value is defined
```typescript
type TourContextType = {
    currentStep: number
    setCurrentStep: React.Dispatch<React.SetStateAction<number>>
}
```
2. Defaults. What to return if no Provider not found in parent components
```typescript
const TourContext = React.createContext<TourContextValue>({
    currentStep: 0
    setCurrentStep: () => ({})
})
```
So, now if you decided to use context without a provider, you will get this defaults

3. Actual values
```
const TourContextProvider = ...
```

2024-01-19 07:05 UTC, SavelevMatthew approved these changes
LGTM

2024-01-19 07:08 UTC, merged