hotfix(condo): add retrying for deliverMessage task
open-condo-software/condo pull request #4327
Opened 2024-01-25 12:30 UTC by VKislov

Before release, you need to delete the task with the old config in production. So that after the release there is no duplication

2024-01-29 07:59 UTC, AleX83Xpert requested changes

2024-01-29 07:59 UTC, AleX83Xpert commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +            for (let retryCounter = 0; retryCounter < 5; retryCounter++) {
Looks like this code will send 5 push messages.
Every loop iteration you rewrite the `stream` variable. After the loop you have another "onResponse" callback. Which stream this callback is?

You need to wait the answer for the first request. If the answer is erroneous you should repeat the request.

2024-01-31 11:10 UTC, pahaz commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +                stream = this.#session.request(headers)
Why not to use await ?

2024-01-31 11:11 UTC, pahaz commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +                    logger.error({ msg: 'sendPush errored', failCounter: retryCounter + 1, headers, options, payload, streamError: error })
use `err` key for error! we need to save tranceback

2024-02-01 12:40 UTC, AleX83Xpert commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +            for (let retryCounter = 0; retryCounter < 5; retryCounter++) {
It's better to move `5` to some constant

2024-02-01 12:49 UTC, AleX83Xpert commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +                if (response instanceof Error) continue
Maybe add some logs?
```suggestion
                if (response instanceof Error) {
                    logger.warn({ msg: '...' })
                    continue
                }
```

2024-02-02 05:43 UTC, AleX83Xpert approved these changes

2024-02-02 05:44 UTC, merged

2024-05-06 19:18 UTC, pahaz commented on apps/condo/domains/notification/adapters/apple/AppleMessaging.js
> +                return resolve(err)
It looks so strange! you should use reject for such things