feature(condo): DOMA-8364 extend user ritesSet to support Property
open-condo-software/condo pull request #4339
Opened 2024-01-31 06:16 UTC by dkoviazin

We need service user to have access to organization Properties:
1. EPS will create properties for new flow
2. SPP will create properties when user accepts offer to publish accruals in condo
3. Registry will use current organization properties to normalize addresses and to highlight that some properties from accrual file are missing

2024-01-31 06:29 UTC, SavelevMatthew commented on apps/condo/domains/user/utils/directAccess/config.js
> +        'Property',
keep order of domains alphabetical)

2024-01-31 06:30 UTC, SavelevMatthew reviewed
Any tests?)

2024-01-31 06:31 UTC, SavelevMatthew commented
You should also modify access checks for a changed model

2024-01-31 06:34 UTC, SavelevMatthew commented
> We need service user to have access to organization Properties:
> 
> 1. EPS will create properties for new flow
> 2. SPP will create properties when user accepts offer to publish accruals in condo
> 3. Registry will use current organization properties to normalize addresses and to highlight that some properties from accrual file are missing

1-2. In this case, aren't the service users also creating an organization? Then they already have access.
3. Registry cannot work without current user, so it's should use user token instead probably.

2024-01-31 06:35 UTC, SavelevMatthew requested changes
Please add real-life tests / explain your decision :)

2024-02-05 04:43 UTC, AleX83Xpert approved these changes

2024-03-25 12:01 UTC, closed without merging