feature/condo/infra-200/sync-replication
open-condo-software/condo pull request #4698
Opened 2024-05-06 09:06 UTC by Gladioluss

feature(condo) INFRA-200: change async replication to sync

2024-05-06 10:31 UTC, sitozzz commented on .helm
Please remove unnecessary submodule update

2024-05-08 09:55 UTC, SavelevMatthew approved these changes

2024-05-13 08:46 UTC, sitozzz requested changes
You have wrong submodule commit pointing in this PR. Please fix this before merge

2024-05-14 09:57 UTC, sitozzz approved these changes

2024-05-17 10:15 UTC, merged