fix(condo): remove dependencies for submodule from condo
open-condo-software/condo pull request #5012
Opened 2024-07-25 11:40 UTC by dkoviazin

1. Added mock files 
2. Removed dots and commas trim

2024-07-25 11:41 UTC, VKislov approved these changes

2024-07-25 12:40 UTC, SavelevMatthew requested changes
Use english examples please.

2024-07-25 17:20 UTC, toplenboren commented on packages/keystone/file/utils.js
> +        //.replace(DOTS_AND_COMMAS_REGEXP, '')
why comments tho?

2024-07-26 11:56 UTC, SavelevMatthew approved these changes

2024-07-26 12:16 UTC, dkoviazin commented on packages/keystone/file/utils.js
> +        //.replace(DOTS_AND_COMMAS_REGEXP, '')
removed

2024-07-26 16:40 UTC, merged