chore(eps): DOMA-1893 check bicrypt build
open-condo-software/condo pull request #5388
Opened 2024-10-23 13:33 UTC by vovaaxeapolla

2024-10-23 13:37 UTC, SavelevMatthew requested changes
You should have only 1 yarn and 1 yarn.lock located in the root of monorepo.

2024-10-28 07:30 UTC, SavelevMatthew commented
Can you use newly added workspace instead of `cd`?

Like:
```
yarn workspace lib-name build && ...
```

Instead of:
```
cd path/to/lib && yarn build && ...
```

2024-10-30 21:24 UTC, SavelevMatthew approved these changes
LGTM. Great job 🔥

2024-10-31 07:22 UTC, dkoviazin approved these changes

2024-10-31 10:52 UTC, merged