hotfix(condo): disable history records creation for Message schema
open-condo-software/condo pull request #5528
Opened 2024-11-22 06:04 UTC by sitozzz

2024-11-22 08:41 UTC, toplenboren approved these changes

2024-11-22 14:29 UTC, dkoviazin approved these changes

2024-11-23 18:30 UTC, SavelevMatthew requested changes
Lets save it as Plan B for now...

2024-11-25 07:07 UTC, sitozzz commented
> Lets save it as Plan B for now...

As you wish)

2024-11-25 07:07 UTC, closed without merging