DOMA-1138 create meters page
open-condo-software/condo pull request #566
Opened 2021-09-13 08:47 UTC by nomerdvadcatpyat

This pr based on  #557 since changes in the scheme are needed here.

![изображение](https://user-images.githubusercontent.com/52532264/133052116-3fc48cde-7326-434c-a84e-5347a6a20243.png)
<img width="1440" alt="изображение" src="https://user-images.githubusercontent.com/52532264/133052306-858c76f7-41e6-4e17-809a-fd3746fb28be.png">
<img width="1440" alt="изображение" src="https://user-images.githubusercontent.com/52532264/133052320-42046d7b-fef2-4295-ac42-2a30a6b9d336.png">
<img width="1440" alt="изображение" src="https://user-images.githubusercontent.com/52532264/133052328-db4168f2-179c-4825-b8cf-bfc433ee7632.png">

What else needs to be done:
- [ ] add number validations on meter reading inputs or find how to use addon with InputNumber
- [ ] research and fix bug related "item id is undefined"

2021-09-13 12:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/createMeterModal/MeterInfo.tsx
> +    return Array.from({ length: 4 }, (_, i) => i + 1)
hard-coded 4?

2021-09-13 12:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/createMeterModal/MeterInfo.tsx
> +import { Button, Col, DatePicker, Form, Input, Row, Select, Space, Typography } from 'antd'
use DatePicker from common components

2021-09-13 12:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/createMeterModal/MeterInfo.tsx
> +    const validations = useValidations()
see comment about validations

2021-09-13 12:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/createMeterModal/ResourcesList.tsx
> +      // TODO(nomerdvadcatpyat): change .hover to .elevated when pr #555 will be merged into master
undone todo

2021-09-13 12:12 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/createMeterModal/ResourcesList.tsx
> +                <Typography.Text strong={true} style={{ fontSize: '16px' }}>{label}</Typography.Text>
hard-coded fontStyle? May be `@condo/domains/common/constants/style` instead

2021-09-13 17:39 UTC, pahaz commented on apps/condo/domains/common/components/UnitInfo.tsx
> +import { useIntl } from '@core/next/intl'
could you please move this component to the nearest domain? Maybe it's the property. The common domain is for non-domain logic and components

2021-09-13 17:44 UTC, pahaz approved these changes

2021-09-14 10:54 UTC, Dimitreee commented on apps/condo/pages/meter/create.tsx
> +                            <Typography.Title level={1} style={{ margin: 0 }}>{PageTitle}</Typography.Title>
you sure u need this?
we got global style which should disable this margin

<img width="469" alt="Screenshot 2021-09-14 at 13 54 06" src="https://user-images.githubusercontent.com/18723798/133245163-4765b788-f06f-49ab-bb4c-e02c5304211b.png">

2021-09-14 11:01 UTC, Dimitreee commented on apps/condo/domains/meter/utils/clientSchema/index.ts
> +export const resourceIdToIcon = {
```suggestion
resourceIdIconMap
```

2021-09-14 11:03 UTC, Dimitreee commented on apps/condo/domains/common/components/icons/MeterIcon.tsx
> +const MeterIconSVG = ({ width = 20, height = 20, bgColor = '#fff' }) => {
use color from style

2021-09-14 11:03 UTC, Dimitreee commented on apps/condo/domains/common/components/icons/AppealIcon.tsx
> +export const AppealIconSVG = ({ width = 20, height = 20, bgColor = '#fff' }) => {
use color from style

2021-09-14 11:04 UTC, Dimitreee commented on apps/condo/domains/meter/components/AccountNumberInput.tsx
> +                <Col span={8} style={{ padding: '80px 0' }}>
css hack detected

2021-09-14 11:18 UTC, Dimitreee commented on apps/condo/domains/meter/components/MeterCard.tsx
> +                                <Typography.Text style={{ fontSize: fontSizes.content }} strong={true}>
you can use shorthand for boolean props

2021-09-21 08:41 UTC, AntonAL reviewed
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2064830/134139982-46a785a1-0d82-4805-9c5d-de352f9b88c3.png">
On meter create page there is a mess of buttons.
Maybe to hide action bar, when there is no account for selected unit?

2021-09-21 08:44 UTC, AntonAL commented
After trying to add wrong account number, modal panel disappears and input is displayed instead.
The same input jumps from modal to form item, it looks strange.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/2064830/134140372-4e6050cd-59cd-4afe-9fda-b3b3de86f498.png">

2021-09-21 09:05 UTC, nomerdvadcatpyat commented
> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/2064830/134139982-46a785a1-0d82-4805-9c5d-de352f9b88c3.png">
> On meter create page there is a mess of buttons. Maybe to hide action bar, when there is no account for selected unit?

Yes, I agree that it will be better, made changes in 7797304

2021-09-21 09:08 UTC, nomerdvadcatpyat commented
> After trying to add wrong account number, modal panel disappears and input is displayed instead.
> The same input jumps from modal to form item, it looks strange.
> <img alt="image" width="689" src="https://user-images.githubusercontent.com/2064830/134140372-4e6050cd-59cd-4afe-9fda-b3b3de86f498.png">

This is done specifically so that after filling out the meter reading, you can make sure that the account number is correct and, if it is not correct, then change it

2021-09-21 11:03 UTC, nomerdvadcatpyat commented on apps/condo/domains/meter/components/AccountNumberInput.tsx
> +                <Col span={8} style={{ padding: '80px 0' }}>
made it through antd grids

2021-09-21 11:16 UTC, SavelevMatthew approved these changes

2021-09-21 11:16 UTC, SavelevMatthew commented on apps/condo/domains/common/hooks/useValidations.ts
> +        pattern: /^\d+(\.?\d+)?$/g,
What about ","....Seems like some meters uses it as separator....so, it's not user friendly :)

2021-09-21 11:16 UTC, SavelevMatthew commented on apps/condo/domains/meter/components/MeterCard.tsx
> +import { useValidations } from '../../common/hooks/useValidations'
`@condo`

2021-09-21 11:16 UTC, SavelevMatthew commented on apps/condo/domains/meter/constants/errors.js
> +const EXISTING_METER_NUMBER = '[unique:alreadyExists:number]'
meter? not intuitive

2021-09-22 03:38 UTC, dkoviazin requested changes

2021-09-22 03:38 UTC, dkoviazin commented on apps/condo/domains/common/components/ActionBar.tsx
> +    left: -24px;
No. You can look at Figma's screens

2021-09-22 04:12 UTC, nomerdvadcatpyat commented on apps/condo/domains/common/components/ActionBar.tsx
> +    left: -24px;
On figma screens action bar look like this:
![изображение](https://user-images.githubusercontent.com/52532264/134282181-b4ccf516-0ab0-4873-9260-4b6d31e5e98e.png)
![изображение](https://user-images.githubusercontent.com/52532264/134282196-cc5afde2-1890-48ac-bee6-ea08d3506c4a.png)

Now it looks like this:
<img width="660" alt="изображение" src="https://user-images.githubusercontent.com/52532264/134282275-4f5ed0ed-045b-4fb3-911c-3be597d9599c.png">

Shouldn't it be shifted to the left?

2021-09-22 04:56 UTC, dkoviazin approved these changes

2021-09-22 05:55 UTC, merged