DOMA-1732 saved modal filters in localStorage
open-condo-software/condo pull request #913
Opened 2021-12-03 08:36 UTC by nomerdvadcatpyat

2021-12-03 09:40 UTC, MrFoxPro requested changes

2021-12-03 09:40 UTC, MrFoxPro commented on apps/condo/domains/common/utils/FiltersStorage.ts
> +        if (isString(filters)) {
You should check whether it is json, not only string. Wrap it to try-catch block

2021-12-03 11:31 UTC, MrFoxPro approved these changes

2021-12-06 08:56 UTC, pahaz approved these changes

2021-12-07 07:13 UTC, merged